// Emit src/config/generated-version.ts from package.json version.
// Replaces the previous inline `node -e` invocation in the prebuild script,
// which constituted an unreviewed code-execution surface between
// prepublishOnly and tsc. Keeping this as a checked-in file ensures the
// script that runs during publish is review-gated like any other source.

import { readFileSync, writeFileSync } from 'node:fs';

const pkg = JSON.parse(readFileSync('package.json', 'utf8'));

const output =
  '// Auto-generated by scripts/generate-version.mjs — do not edit\n' +
  `export const SDK_CORE_VERSION = '${pkg.version}';\n`;

writeFileSync('src/config/generated-version.ts', output);
